import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';
import Provider from "./providers"; 
import { config,getConfig } from "./config";
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
   const initialState = cookieToInitialState(
    getConfig(),
    (await headers()).get('cookie')
  );

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-950 text-gray-100`}>
    <div className="bg-[#121212]">   <span></span>
   <span></span>
   <span></span>
   <span></span>
   <span></span>
   <span></span>
   <span></span>
</div >
        <div className="pt-[100px] sticky" >
 
          <Provider initialState={initialState}>
         
            {children}</Provider>
        </div >
      </body>
    </html>
  );
}
